
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 69 [current_design]
set_property CONFIG_VOLTAGE 2.5 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR no [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
#set_property BITSTREAM.STARTUP.DONE_CYCLE 6 [current_design]
#set_property BITSTREAM.STARTUP.GTS_CYCLE DONE [current_design]


#set_property PACKAGE_PIN AJ21 [get_ports {p_adc_frameclk_in[0][p]}]
#set_property PACKAGE_PIN AK22 [get_ports {p_adc_bitclk_in[0][p]}]
#set_property PACKAGE_PIN AL20 [get_ports {p_adc_lg_data_in[0][p]}]
#set_property PACKAGE_PIN AJ20 [get_ports {p_adc_hg_data_in[0][p]}]
#set_property PACKAGE_PIN D23 [get_ports {p_adc_frameclk_in[4][p]}]
#set_property PACKAGE_PIN E22 [get_ports {p_adc_bitclk_in[4][p]}]
#set_property PACKAGE_PIN B21 [get_ports {p_adc_lg_data_in[4][p]}]
#set_property PACKAGE_PIN C21 [get_ports {p_adc_hg_data_in[4][p]}]
#set_property PACKAGE_PIN G17 [get_ports {p_adc_fr      ameclk_in[5][p]}]
#set_property PACKAGE_PIN F18 [get_ports {p_adc_bitclk_in[5][p]}]
#set_property PACKAGE_PIN G15 [get_ports {p_adc_lg_data_in[5][p]}]
#set_property PACKAGE_PIN G19 [get_ports {p_adc_hg_data_in[5][p]}]
#set_property PACKAGE_PIN AJ29 [get_ports {p_adc_frameclk_in[1][p]}]
#set_property PACKAGE_PIN AK31 [get_ports {p_adc_bitclk_in[1][p]}]
#set_property PACKAGE_PIN AJ30 [get_ports {p_adc_lg_data_in[1][p]}]
#set_property PACKAGE_PIN AH33 [get_ports {p_adc_hg_data_in[1][p]}]
#set_property PACKAGE_PIN H11 [get_ports {p_adc_frameclk_in[3][p]}]
#set_property PACKAGE_PIN H12 [get_ports {p_adc_bitclk_in[3][p]}]
#set_property PACKAGE_PIN K11 [get_ports {p_adc_lg_data_in[3][p]}]
#set_property PACKAGE_PIN L13 [get_ports {p_adc_hg_data_in[3][p]}]
#set_property PACKAGE_PIN AA24 [get_ports {p_adc_gbtx_frameclk_in[2][p]}]
#set_property PACKAGE_PIN AL30 [get_ports {p_adc_gbtx_frameclk_in[1][p]}]
#set_property PACKAGE_PIN AH22 [get_ports {p_adc_gbtx_frameclk_in[0][p]}]
#set_property PACKAGE_PIN G10 [get_ports {p_adc_gbtx_frameclk_in[3][p]}]
#set_property PACKAGE_PIN D24 [get_ports {p_adc_gbtx_frameclk_in[4][p]}]
#set_property PACKAGE_PIN E18 [get_ports {p_adc_gbtx_frameclk_in[5][p]}]
#set_property PACKAGE_PIN W23 [get_ports {p_adc_frameclk_in[2][p]}]
#set_property PACKAGE_PIN W25 [get_ports {p_adc_bitclk_in[2][p]}]
#set_property PACKAGE_PIN U21 [get_ports {p_adc_lg_data_in[2][p]}]
#set_property PACKAGE_PIN V22 [get_ports {p_adc_hg_data_in[2][p]}]

set_property PACKAGE_PIN AK22 [get_ports {p_adc_frameclk_in[5][p]}]
set_property PACKAGE_PIN AJ21 [get_ports {p_adc_bitclk_in[5][p]}]
set_property PACKAGE_PIN AL20 [get_ports {p_adc_lg_data_in[5][p]}]
set_property PACKAGE_PIN AJ20 [get_ports {p_adc_hg_data_in[5][p]}]
set_property PACKAGE_PIN E22 [get_ports {p_adc_frameclk_in[1][p]}]
set_property PACKAGE_PIN D23 [get_ports {p_adc_bitclk_in[1][p]}]
set_property PACKAGE_PIN B21 [get_ports {p_adc_lg_data_in[1][p]}]
set_property PACKAGE_PIN C21 [get_ports {p_adc_hg_data_in[1][p]}]
set_property PACKAGE_PIN F18 [get_ports {p_adc_frameclk_in[0][p]}]
set_property PACKAGE_PIN G17 [get_ports {p_adc_bitclk_in[0][p]}]
set_property PACKAGE_PIN G15 [get_ports {p_adc_lg_data_in[0][p]}]
set_property PACKAGE_PIN G19 [get_ports {p_adc_hg_data_in[0][p]}]
set_property PACKAGE_PIN AK31 [get_ports {p_adc_frameclk_in[4][p]}]
set_property PACKAGE_PIN AJ29 [get_ports {p_adc_bitclk_in[4][p]}]
set_property PACKAGE_PIN AJ30 [get_ports {p_adc_lg_data_in[4][p]}]
set_property PACKAGE_PIN AH33 [get_ports {p_adc_hg_data_in[4][p]}]
set_property PACKAGE_PIN H12 [get_ports {p_adc_frameclk_in[2][p]}]
set_property PACKAGE_PIN H11 [get_ports {p_adc_bitclk_in[2][p]}]
set_property PACKAGE_PIN K11 [get_ports {p_adc_lg_data_in[2][p]}]
set_property PACKAGE_PIN L13 [get_ports {p_adc_hg_data_in[2][p]}]
set_property PACKAGE_PIN AA24 [get_ports {p_adc_gbtx_frameclk_in[3][p]}]
set_property PACKAGE_PIN AL30 [get_ports {p_adc_gbtx_frameclk_in[4][p]}]
set_property PACKAGE_PIN AH22 [get_ports {p_adc_gbtx_frameclk_in[5][p]}]
set_property PACKAGE_PIN G10 [get_ports {p_adc_gbtx_frameclk_in[2][p]}]
set_property PACKAGE_PIN D24 [get_ports {p_adc_gbtx_frameclk_in[1][p]}]
set_property PACKAGE_PIN E18 [get_ports {p_adc_gbtx_frameclk_in[0][p]}]
set_property PACKAGE_PIN W25 [get_ports {p_adc_frameclk_in[3][p]}]
set_property PACKAGE_PIN W23 [get_ports {p_adc_bitclk_in[3][p]}]
set_property PACKAGE_PIN U21 [get_ports {p_adc_lg_data_in[3][p]}]
set_property PACKAGE_PIN V22 [get_ports {p_adc_hg_data_in[3][p]}]

set_property DATA_RATE DDR [get_ports {p_adc_frameclk_in[5][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_bitclk_in[5][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_lg_data_in[5][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_hg_data_in[5][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_frameclk_in[1][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_bitclk_in[1][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_lg_data_in[1][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_hg_data_in[1][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_frameclk_in[0][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_bitclk_in[0][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_lg_data_in[0][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_hg_data_in[0][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_frameclk_in[4][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_bitclk_in[4][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_lg_data_in[4][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_hg_data_in[4][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_frameclk_in[2][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_bitclk_in[2][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_lg_data_in[2][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_hg_data_in[2][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_gbtx_frameclk_in[3][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_gbtx_frameclk_in[4][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_gbtx_frameclk_in[5][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_gbtx_frameclk_in[2][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_gbtx_frameclk_in[1][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_gbtx_frameclk_in[0][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_frameclk_in[3][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_bitclk_in[3][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_lg_data_in[3][p]}]
set_property DATA_RATE DDR [get_ports {p_adc_hg_data_in[3][p]}]

set_property PACKAGE_PIN AN14 [get_ports {p_tpl_out[q0][p]}]
set_property PACKAGE_PIN AP14 [get_ports {p_tpl_out[q0][n]}]
set_property PACKAGE_PIN AN19 [get_ports {p_tph_out[q0][p]}]
set_property PACKAGE_PIN AP18 [get_ports {p_tph_out[q0][n]}]
set_property PACKAGE_PIN AM17 [get_ports {p_tpl_out[q1][p]}]
set_property PACKAGE_PIN AN16 [get_ports {p_tpl_out[q1][n]}]
set_property PACKAGE_PIN AN18 [get_ports {p_tph_out[q1][p]}]
set_property PACKAGE_PIN AN17 [get_ports {p_tph_out[q1][n]}]
set_property PACKAGE_PIN AP19 [get_ports {p_gbtx_rxready_in[0]}]
set_property PACKAGE_PIN AL19 [get_ports {p_gbtx_i2c_sda_inout[0]}]
set_property PACKAGE_PIN AM19 [get_ports {p_gbtx_i2c_scl_inout[0]}]
set_property PACKAGE_PIN AJ18 [get_ports {p_gbt_tp_q0_clk40_local_in[p]}]
set_property PACKAGE_PIN AK17 [get_ports {p_gbt_tp_q1_clk40_local_in[p]}]
set_property PACKAGE_PIN AH18 [get_ports {p_gbt_cfgbus_clk40_local_in[p]}]
set_property PACKAGE_PIN AG17 [get_ports {p_cfgbus_data_local_in[6][p]}]
set_property PACKAGE_PIN AG15 [get_ports {p_cfgbus_data_local_in[0][p]}]
set_property PACKAGE_PIN AH14 [get_ports {p_gbtx_configsel_out[0]}]
set_property PACKAGE_PIN AD19 [get_ports {p_cfgbus_data_local_in[7][p]}]
set_property PACKAGE_PIN AF15 [get_ports {p_cfgbus_data_local_in[4][p]}]
set_property PACKAGE_PIN AE18 [get_ports {p_cfgbus_data_local_in[3][p]}]
set_property PACKAGE_PIN AE16 [get_ports {p_cfgbus_data_local_in[2][p]}]
set_property PACKAGE_PIN AE17 [get_ports {p_cfgbus_data_local_in[1][p]}]
set_property PACKAGE_PIN AD16 [get_ports {p_cfgbus_data_local_in[5][p]}]
set_property PACKAGE_PIN AD14 [get_ports {p_gbtx_datavalid_in[0]}]

set_property PACKAGE_PIN AC29 [get_ports {p_pgood_in[mb_2v5_1v2]}]
set_property PACKAGE_PIN AD30 [get_ports {p_gbt_mb_q0_clk40_local_in[p]}]
set_property PACKAGE_PIN AC31 [get_ports {p_gbt_mb_q1_clk40_local_in[p]}]
set_property PACKAGE_PIN V33 [get_ports {p_sdata_out[q1][p]}]
set_property PACKAGE_PIN Y31 [get_ports {p_sdata_in[q1][p]}]
set_property PACKAGE_PIN U34 [get_ports {p_ssel_out[q1][p]}]
set_property PACKAGE_PIN V31 [get_ports {p_sclk_out[q1][p]}]
set_property PACKAGE_PIN AA33 [get_ports {p_pgood_in[mb_5v0_1v8]}]
set_property PACKAGE_PIN AC34 [get_ports {p_sdata_out[q0][p]}]
set_property PACKAGE_PIN W33 [get_ports {p_sdata_in[q0][p]}]
set_property PACKAGE_PIN AA34 [get_ports {p_ssel_out[q0][p]}]
set_property PACKAGE_PIN AC33 [get_ports {p_sclk_out[q0][p]}]
set_property PACKAGE_PIN V32 [get_ports {p_pgood_in[mb_5v0_n_3v3]}]
set_property PACKAGE_PIN AN13 [get_ports {p_md_number_in[3]}]
set_property PACKAGE_PIN AP13 [get_ports {p_md_number_in[2]}]
set_property PACKAGE_PIN AP11 [get_ports {p_md_number_in[1]}]
set_property PACKAGE_PIN AP10 [get_ports {p_md_number_in[0]}]
set_property PACKAGE_PIN AM12 [get_ports {p_mb_fpga_reset_low[q0]}]
set_property PACKAGE_PIN AN12 [get_ports {p_mb_fpga_reset_low[q1]}]
set_property PACKAGE_PIN AK11 [get_ports {p_pgood_in[db_1v8_2v5]}]
set_property PACKAGE_PIN AE13 [get_ports p_tdo_remote_in]
#set_property PACKAGE_PIN AE12 [get_ports {p_integrator_scl_inout[q0]}]
#set_property PACKAGE_PIN AF12 [get_ports {p_integrator_sda_inout[q0]}]
#set_property PACKAGE_PIN AD11 [get_ports {p_integrator_sda_inout[q1]}]
#set_property PACKAGE_PIN AE11 [get_ports {p_integrator_scl_inout[q1]}]
set_property PACKAGE_PIN AE11 [get_ports {p_integrator_scl_inout[q0]}]
set_property PACKAGE_PIN AD11 [get_ports {p_integrator_sda_inout[q0]}]
set_property PACKAGE_PIN AF12 [get_ports {p_integrator_sda_inout[q1]}]
set_property PACKAGE_PIN AE12 [get_ports {p_integrator_scl_inout[q1]}]
set_property PACKAGE_PIN AJ11 [get_ports {p_pgood_in[db_1v0_0v95]}]
set_property PACKAGE_PIN AF10 [get_ports {p_osc_clk_in[p]}]
set_property PACKAGE_PIN AG9 [get_ports p_sem_uart_rx_in]
set_property PACKAGE_PIN AF9 [get_ports p_sem_uart_tx_out]
set_property PACKAGE_PIN AF8 [get_ports p_debug_interface_uart_rx_in]
set_property IOSTANDARD LVCMOS25 [get_ports p_debug_interface_uart_rx_in]
set_property PACKAGE_PIN AE8 [get_ports p_debug_interface_uart_tx_out]
set_property IOSTANDARD LVCMOS25 [get_ports p_debug_interface_uart_tx_out]
set_property PACKAGE_PIN AJ10 [get_ports {p_pgood_in[mb_10v0]}]
set_property PACKAGE_PIN AN8 [get_ports {p_pgood_in[db_1v2_5v0]}]
set_property PACKAGE_PIN AP8 [get_ports {p_pgood_in[db_1v5_3v3]}]
set_property PACKAGE_PIN AM9 [get_ports {p_db_side_in[0]}]
set_property PACKAGE_PIN H27 [get_ports {p_leds_out[2]}]
set_property PACKAGE_PIN G27 [get_ports {p_leds_out[1]}]
set_property PACKAGE_PIN G26 [get_ports {p_leds_out[0]}]
set_property PACKAGE_PIN K26 [get_ports {p_xadc_analog_in[vaux15][p]}]
set_property PACKAGE_PIN K27 [get_ports {p_xadc_analog_in[vaux15][n]}]
set_property PACKAGE_PIN J24 [get_ports {p_xadc_analog_in[vaux7][p]}]
set_property PACKAGE_PIN J25 [get_ports {p_xadc_analog_in[vaux7][n]}]
set_property PACKAGE_PIN J26 [get_ports {p_xadc_analog_in[vaux14][p]}]
set_property PACKAGE_PIN H26 [get_ports {p_xadc_analog_in[vaux14][n]}]
set_property PACKAGE_PIN M27 [get_ports {p_xadc_analog_in[vaux13][p]}]
set_property PACKAGE_PIN L27 [get_ports {p_xadc_analog_in[vaux13][n]}]
set_property PACKAGE_PIN J23 [get_ports {p_xadc_analog_in[vaux6][p]}]
set_property PACKAGE_PIN H24 [get_ports {p_xadc_analog_in[vaux6][n]}]
set_property PACKAGE_PIN L23 [get_ports {p_xadc_analog_in[vaux5][p]}]
set_property PACKAGE_PIN L24 [get_ports {p_xadc_analog_in[vaux5][n]}]
set_property PACKAGE_PIN L25 [get_ports {p_xadc_analog_in[vaux12][p]}]
set_property PACKAGE_PIN K25 [get_ports {p_xadc_analog_in[vaux12][n]}]
set_property PACKAGE_PIN L22 [get_ports {p_xadc_analog_in[vaux4][p]}]
set_property PACKAGE_PIN K23 [get_ports {p_xadc_analog_in[vaux4][n]}]
set_property PACKAGE_PIN T27 [get_ports {p_xadc_analog_in[vaux11][p]}]
set_property PACKAGE_PIN R27 [get_ports {p_xadc_analog_in[vaux11][n]}]
set_property PACKAGE_PIN T24 [get_ports {p_xadc_analog_in[vaux3][p]}]
set_property PACKAGE_PIN T25 [get_ports {p_xadc_analog_in[vaux3][n]}]
set_property PACKAGE_PIN R25 [get_ports {p_xadc_analog_in[vaux10][p]}]
set_property PACKAGE_PIN R26 [get_ports {p_xadc_analog_in[vaux10][n]}]
set_property PACKAGE_PIN R23 [get_ports {p_xadc_analog_in[vaux2][p]}]
set_property PACKAGE_PIN P23 [get_ports {p_xadc_analog_in[vaux2][n]}]
set_property PACKAGE_PIN N27 [get_ports {p_leds_out[3]}]
set_property PACKAGE_PIN N22 [get_ports {p_xadc_analog_in[vaux9][p]}]
set_property PACKAGE_PIN M22 [get_ports {p_xadc_analog_in[vaux9][n]}]
set_property PACKAGE_PIN P20 [get_ports {p_xadc_analog_in[vaux1][p]}]
set_property PACKAGE_PIN P21 [get_ports {p_xadc_analog_in[vaux1][n]}]
set_property PACKAGE_PIN R21 [get_ports {p_xadc_analog_in[vaux8][p]}]
set_property PACKAGE_PIN R22 [get_ports {p_xadc_analog_in[vaux8][n]}]
set_property PACKAGE_PIN M20 [get_ports {p_xadc_analog_in[vaux0][p]}]
set_property PACKAGE_PIN L20 [get_ports {p_xadc_analog_in[vaux0][n]}]

set_property PACKAGE_PIN T5 [get_ports {p_gth_refclk_gbtx_local_in[1][n]}]
set_property PACKAGE_PIN R3 [get_ports {p_tx_sfp_out[1][n]}]
set_property PACKAGE_PIN AM6 [get_ports {p_tx_sfp_out[0][p]}]
set_property PACKAGE_PIN AD6 [get_ports {p_gth_refclk_gbtx_local_in[0][p]}]
#set_property PACKAGE_PIN AC4 [get_ports {p_tx_sfp_out[0][p]}]
#set_property PACKAGE_PIN Y6 [get_ports {p_gth_refclk_gbtx_local_in[0][p]}


set_property IOSTANDARD LVDS_25 [get_ports {p_osc_clk_in[p]}]
set_property IOSTANDARD LVDS_25 [get_ports {p_osc_clk_in[n]}]

set_property IOSTANDARD LVCMOS18 [get_ports {p_gbtx_configsel_out[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {p_gbtx_datavalid_in[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {p_gbtx_i2c_scl_inout[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {p_gbtx_i2c_sda_inout[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {p_gbtx_rxready_in[0]}]
set_property IOSTANDARD LVDS [get_ports {p_tpl_out[q1][p]}]
set_property IOSTANDARD LVDS [get_ports {p_tph_out[q0][p]}]
set_property IOSTANDARD LVDS [get_ports {p_tph_out[q1][p]}]
set_property IOSTANDARD LVDS [get_ports {p_tph_out[q1][n]}]
set_property IOSTANDARD LVDS [get_ports {p_tpl_out[q0][p]}]
set_property IOSTANDARD LVDS [get_ports {p_tpl_out[q0][n]}]
set_property IOSTANDARD LVDS [get_ports {p_tpl_out[q1][n]}]
set_property IOSTANDARD LVDS [get_ports {p_tph_out[q0][n]}]
set_property IOSTANDARD LVDS [get_ports {p_sclk_out[q1][p]}]
set_property IOSTANDARD LVDS [get_ports {p_sclk_out[q1][n]}]
set_property IOSTANDARD LVDS [get_ports {p_sdata_out[q1][p]}]
set_property IOSTANDARD LVDS [get_ports {p_sdata_out[q1][n]}]
set_property IOSTANDARD LVDS [get_ports {p_ssel_out[q1][n]}]
set_property IOSTANDARD LVDS [get_ports {p_ssel_out[q1][p]}]
set_property IOSTANDARD LVDS [get_ports {p_sdata_out[q0][p]}]
set_property IOSTANDARD LVDS [get_ports {p_ssel_out[q0][p]}]
set_property IOSTANDARD LVDS [get_ports {p_sdata_out[q0][n]}]
set_property IOSTANDARD LVDS [get_ports {p_ssel_out[q0][n]}]
set_property IOSTANDARD LVDS [get_ports {p_sclk_out[q0][p]}]
set_property IOSTANDARD LVDS [get_ports {p_sdata_in[q1][n]}]
set_property IOSTANDARD LVDS [get_ports {p_sdata_in[q0][p]}]
set_property IOSTANDARD LVDS [get_ports {p_sdata_in[q1][p]}]
set_property IOSTANDARD LVDS [get_ports {p_sdata_in[q0][n]}]
set_property IOSTANDARD LVDS [get_ports {p_sclk_out[q0][n]}]
set_property IOSTANDARD LVCMOS25 [get_ports {p_pgood_in[db_1v8_2v5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {p_integrator_sda_inout[q1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {p_md_number_in[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {p_md_number_in[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {p_md_number_in[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {p_integrator_scl_inout[q1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {p_integrator_scl_inout[q0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {p_mb_fpga_reset_low[q0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {p_pgood_in[db_1v0_0v95]}]
set_property IOSTANDARD LVCMOS25 [get_ports {p_integrator_sda_inout[q0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {p_mb_fpga_reset_low[q1]}]
set_property IOSTANDARD LVCMOS25 [get_ports p_tdo_remote_in]
set_property IOSTANDARD LVCMOS25 [get_ports {p_md_number_in[3]}]
set_property DRIVE 12 [get_ports {p_integrator_sda_inout[q1]}]
set_property DRIVE 12 [get_ports {p_integrator_scl_inout[q1]}]
set_property DRIVE 12 [get_ports {p_integrator_scl_inout[q0]}]
set_property DRIVE 12 [get_ports {p_mb_fpga_reset_low[q0]}]
set_property DRIVE 12 [get_ports {p_integrator_sda_inout[q0]}]
set_property DRIVE 12 [get_ports {p_mb_fpga_reset_low[q1]}]
set_property SLEW SLOW [get_ports {p_integrator_sda_inout[q1]}]
set_property SLEW SLOW [get_ports {p_integrator_scl_inout[q1]}]
set_property SLEW SLOW [get_ports {p_integrator_scl_inout[q0]}]
set_property SLEW SLOW [get_ports {p_mb_fpga_reset_low[q0]}]
set_property SLEW SLOW [get_ports {p_integrator_sda_inout[q0]}]
set_property SLEW SLOW [get_ports {p_mb_fpga_reset_low[q1]}]
set_property IOSTANDARD LVCMOS25 [get_ports p_sem_uart_rx_in]
set_property IOSTANDARD LVCMOS25 [get_ports p_sem_uart_tx_out]
set_property DRIVE 12 [get_ports p_debug_interface_uart_tx_out]
set_property DRIVE 12 [get_ports p_sem_uart_tx_out]
set_property SLEW SLOW [get_ports p_debug_interface_uart_tx_out]
set_property SLEW SLOW [get_ports p_sem_uart_tx_out]
set_property IOSTANDARD LVCMOS25 [get_ports {p_db_side_in[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {p_pgood_in[db_1v2_5v0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {p_pgood_in[db_1v5_3v3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_leds_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_leds_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_leds_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_leds_out[3]}]

set_property IOSTANDARD LVCMOS25 [get_ports {p_pgood_in[mb_10v0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {p_pgood_in[mb_5v0_1v8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {p_pgood_in[mb_5v0_n_3v3]}]
set_property PACKAGE_PIN AG31 [get_ports {p_gbt_mb_q0_clk40_out[p]}]
set_property IOSTANDARD LVDS [get_ports {p_gbt_mb_q0_clk40_out[p]}]
set_property IOSTANDARD LVDS [get_ports {p_gbt_mb_q0_clk40_out[n]}]
set_property PACKAGE_PIN AE32 [get_ports {p_gbt_mb_q1_clk40_out[p]}]
set_property IOSTANDARD LVDS [get_ports {p_gbt_mb_q1_clk40_out[p]}]
set_property IOSTANDARD LVDS [get_ports {p_gbt_mb_q1_clk40_out[n]}]
set_property IOSTANDARD LVCMOS18 [get_ports {p_pgood_in[mb_2v5_1v2]}]



#sda ad9 cs0_p
#scl ad8 cs0_n


set_property ASYNC_REG true [get_cells {i_db6_clock_interface/gen_reset_sync_links[1].i_db6_reset_synchronizer/gen_x_clk_steps.s_reset_register_reg[0]}]
set_property ASYNC_REG true [get_cells {i_db6_clock_interface/gen_reset_sync_links[1].i_db6_reset_synchronizer/gen_x_clk_steps.s_reset_reg}]


set_property IOSTANDARD LVCMOS25 [get_ports p_adc_channel_pedestal_test_overflow_out]
set_property PACKAGE_PIN AE10 [get_ports p_adc_channel_pedestal_test_overflow_out]
set_property PACKAGE_PIN AD10 [get_ports p_adc_channel_pedestal_test_underflow_out]
set_property IOSTANDARD LVCMOS25 [get_ports p_adc_channel_pedestal_test_underflow_out]

set_property CLKFBOUT_MULT 12 [get_cells i_db6_clock_interface/i_pll_osc_clk/inst/plle3_adv_inst]
set_property CLKOUT0_DIVIDE 30 [get_cells i_db6_clock_interface/i_pll_osc_clk/inst/plle3_adv_inst]
set_property CLKOUT1_DIVIDE 6 [get_cells i_db6_clock_interface/i_pll_osc_clk/inst/plle3_adv_inst]
set_property MAX_FANOUT_MODE CLOCK_REGION [get_nets {i_db6_gbtx_interface/i_db6_cfgbus_interface/db6_cfgbus_interface_decoder_iddr_local/gen_tmr_disabled.i_db6_cfgbus_interface_decoder_iddr/p_bcr_out[bcr_locked]}]
set_property FORCE_MAX_FANOUT 1 [get_nets {i_db6_gbtx_interface/i_db6_cfgbus_interface/db6_cfgbus_interface_decoder_iddr_local/gen_tmr_disabled.i_db6_cfgbus_interface_decoder_iddr/p_bcr_out[bcr_locked]}]
set_property LUT_REMAP false [get_cells {i_db6_clock_interface/s_clknet_out[gbt_cdc_counter_array][0]_inst}]
set_property LUT_REMAP false [get_cells {i_db6_clock_interface/s_clknet_out[gbt_cdc_counter_array][0]_inst__0}]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets s_clknet[osc_clk40]]

#set_property PACKAGE_PIN AD9 [get_ports p_cht8305c_sda_inout]
set_property PACKAGE_PIN AD9 [get_ports p_cht8305c_sda_inout]
set_property IOSTANDARD LVCMOS25 [get_ports p_cht8305c_sda_inout]
#set_property PACKAGE_PIN AD8 [get_ports p_cht8305c_scl_inout]
set_property PACKAGE_PIN AD8 [get_ports p_cht8305c_scl_inout]
set_property IOSTANDARD LVCMOS25 [get_ports p_cht8305c_scl_inout]
#set_property PULLUP true [get_ports p_cht8305c_scl_inout]
#set_property PULLUP true [get_ports p_cht8305c_sda_inout]

set_property IOSTANDARD LVCMOS33 [get_ports {p_sfp_abs_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_sfp_abs_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_sfp_i2c_scl_inout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_sfp_i2c_scl_inout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_sfp_i2c_sda_inout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_sfp_i2c_sda_inout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_sfp_los_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_sfp_los_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_sfp_tx_fault_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_sfp_tx_fault_in[0]}]
set_property DRIVE 12 [get_ports {p_sfp_i2c_scl_inout[1]}]
set_property DRIVE 12 [get_ports {p_sfp_i2c_scl_inout[0]}]
set_property DRIVE 12 [get_ports {p_sfp_i2c_sda_inout[1]}]
set_property DRIVE 12 [get_ports {p_sfp_i2c_sda_inout[0]}]
set_property SLEW SLOW [get_ports {p_sfp_i2c_scl_inout[1]}]
set_property SLEW SLOW [get_ports {p_sfp_i2c_scl_inout[0]}]
set_property SLEW SLOW [get_ports {p_sfp_i2c_sda_inout[1]}]
set_property SLEW SLOW [get_ports {p_sfp_i2c_sda_inout[0]}]
set_property PACKAGE_PIN M26 [get_ports {p_sfp_abs_in[0]}]
set_property PACKAGE_PIN M24 [get_ports {p_sfp_abs_in[1]}]
set_property PACKAGE_PIN K20 [get_ports {p_sfp_i2c_scl_inout[1]}]
set_property PACKAGE_PIN P26 [get_ports {p_sfp_i2c_scl_inout[0]}]
set_property PACKAGE_PIN N26 [get_ports {p_sfp_i2c_sda_inout[0]}]
set_property PACKAGE_PIN H23 [get_ports {p_sfp_i2c_sda_inout[1]}]
set_property PACKAGE_PIN G25 [get_ports {p_sfp_tx_fault_in[1]}]
set_property PACKAGE_PIN K21 [get_ports {p_sfp_tx_fault_in[0]}]
set_property PACKAGE_PIN N24 [get_ports {p_sfp_los_in[1]}]
set_property PACKAGE_PIN M25 [get_ports {p_sfp_los_in[0]}]

set_property IOSTANDARD SLVS_400_18 [get_ports {p_gbt_tp_q0_clk40_local_in[p]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_gbt_tp_q0_clk40_local_in[n]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_gbt_cfgbus_clk40_local_in[p]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_gbt_cfgbus_clk40_local_in[n]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_cfgbus_data_local_in[0][p]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_cfgbus_data_local_in[0][n]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_cfgbus_data_local_in[1][p]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_cfgbus_data_local_in[1][n]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_cfgbus_data_local_in[2][p]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_cfgbus_data_local_in[2][n]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_cfgbus_data_local_in[3][p]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_cfgbus_data_local_in[3][n]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_cfgbus_data_local_in[4][p]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_cfgbus_data_local_in[4][n]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_cfgbus_data_local_in[5][p]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_cfgbus_data_local_in[5][n]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_cfgbus_data_local_in[6][p]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_cfgbus_data_local_in[6][n]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_cfgbus_data_local_in[7][p]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_cfgbus_data_local_in[7][n]}]

set_property IOSTANDARD SLVS_400_18 [get_ports {p_gbt_cis_hss_clk80_local_in[p]}]
set_property IOSTANDARD SLVS_400_18 [get_ports {p_gbt_cis_hss_clk80_local_in[n]}]
