#vivado 2022.2
# Brief project description here

#   Copyright 2018-2026 The University of Birmingham
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

[parameters]
MAX_THREADS = 4

[main]
PART = xcku035-ffva1156-1-c
CORECONTAINER.ENABLE=1
IP_REPO_PATHS=src/ip/vivado_2025_2


[impl_1]
STEPS.PHYS_OPT_DESIGN.IS_ENABLED=1
STEPS.PHYS_OPT_DESIGN.TCL.PRE=constraints/pre-implementation.tcl
STEPS.PLACE_DESIGN.TCL.PRE=constraints/pre-implementation.tcl
STEPS.ROUTE_DESIGN.TCL.PRE=constraints/pre-implementation.tcl
STEPS.WRITE_BITSTREAM.ARGS.BIN_FILE=1
STEPS.WRITE_BITSTREAM.ARGS.LOGIC_LOCATION_FILE=1
STEPS.WRITE_BITSTREAM.ARGS.MASK_FILE=1
STEPS.WRITE_BITSTREAM.ARGS.RAW_BITFILE=1

[hog]
ALLOW_FAIL_ON_CONF=False
ALLOW_FAIL_ON_GIT=False
ALLOW_FAIL_ON_LIST=False

